Repository dlr-pa/oac, pull requests merged in 2024-11, with the labels that each got.

#21 Bug fix for contrails
  openairclim/main.py
Labels: module: contrails

#23 Adds single flight capability
  example/example.toml
  openairclim/calc_cont.py
  openairclim/main.py
  openairclim/read_config.py
  openairclim/read_netcdf.py
  tests/calc_cont_test.py
  tests/read_config_test.py
Labels: type: feature, module: contrails

#46 Interpolation between base_inv_dict years for contrail climate impact calculations of single flights
  openairclim/calc_cont.py
  openairclim/main.py
  tests/calc_cont_test.py
Labels: type: feature, module: contrails

#47 Create issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: type: chore

#49 Feature/default co2 rf method
  docs/source/openairclim.rst
  environment_dev.yaml
  environment_minimal.yaml
  example/example.toml
  openairclim/read_config.py
  setup.py
  tests/read_config_test.py
Labels: module: core
